from __future__ import annotations

import re
import sqlite3
from pathlib import Path
from typing import Any

from .atomic_io import write_text_atomic
from .campaign import Campaign
from .card_registry import CardRegistry, get_default_card_registry
from .db import entity_subtype_visibility_sql, get_meta, get_player_entity_id
from .entity_access import read_entity
from .redaction import hidden_entity_refs
from .redaction import redact_entity_refs
from .render import append_item_profile_sections, display_key, display_label, format_quantity, format_value, parse_json
from .time_weather import format_time_brief, format_weather_brief
from .visibility import (
    PLAYER_VIEW,
    clock_visibility_sql,
    ensure_visibility_sql_functions,
    entity_not_archived_sql,
    entity_visibility_sql,
    normalize_visibility_view,
    normalized_text_sql,
)


GENERATED_MARKER = "<!-- generated by rpg_engine render-cards; source=data/game.sqlite -->"

CHARACTER_PROFILE_KEYS = (
    "分类",
    "体型",
    "肤色",
    "发色",
    "皮肤细节",
    "视觉/情绪",
    "居所",
    "语言/沟通",
    "命名交换",
    "同伴",
    "互动记录",
)


def write_cards(
    campaign: Campaign,
    conn: sqlite3.Connection,
    *,
    clean: bool = True,
    index_view: str = PLAYER_VIEW,
) -> list[Path]:
    registry = get_default_card_registry()
    cards_root = campaign.cards_path
    cards_root.mkdir(parents=True, exist_ok=True)
    ensure_visibility_sql_functions(conn)
    entity_visibility_clause = entity_visibility_sql(index_view, "e")
    subtype_visibility_clause = entity_subtype_visibility_sql(index_view, "e", "c")

    rows = conn.execute(
        f"""
        select e.*
        from entities e
        left join clocks c on c.entity_id = e.id
        where {entity_not_archived_sql("e")}
          {entity_visibility_clause}
          {subtype_visibility_clause}
        order by name
        """
    ).fetchall()
    rows = sorted(rows, key=lambda row: card_sort_key(row, registry))

    written: list[Path] = []
    target_paths: set[Path] = set()
    for row in rows:
        relative_path = card_relative_path(row, registry)
        path = cards_root / relative_path
        path.parent.mkdir(parents=True, exist_ok=True)
        write_text_atomic(path, render_card(conn, row, registry) + "\n")
        written.append(path)
        target_paths.add(path.resolve())

    index_path = cards_root / "INDEX.md"
    write_text_atomic(index_path, render_card_index(campaign, conn, rows, view=index_view, registry=registry) + "\n")
    written.insert(0, index_path)
    target_paths.add(index_path.resolve())
    if clean:
        remove_generated_cards(cards_root, keep=target_paths)
    return written


def remove_generated_cards(cards_root: Path, *, keep: set[Path] | None = None) -> None:
    keep = keep or set()
    for path in cards_root.rglob("*.md"):
        if path.resolve() in keep:
            continue
        if path.name == "INDEX.md":
            path.unlink()
            continue
        try:
            first_line = path.read_text(encoding="utf-8").splitlines()[0]
        except (OSError, IndexError, UnicodeDecodeError):
            continue
        if first_line == GENERATED_MARKER:
            path.unlink()


def card_relative_path(entity: sqlite3.Row, registry: CardRegistry | None = None) -> Path:
    directory = card_directory(str(entity["type"]), registry)
    return Path(directory) / f"{safe_filename(entity['id'])}.md"


def card_directory(entity_type: str, registry: CardRegistry | None = None) -> str:
    registry = registry or get_default_card_registry()
    return registry.card_dir(entity_type)


def card_sort_key(entity: sqlite3.Row, registry: CardRegistry | None = None) -> tuple[int, str, str]:
    registry = registry or get_default_card_registry()
    return registry.sort_key(str(entity["type"]), str(entity["name"] or ""))


def safe_filename(value: str) -> str:
    text = value.replace(":", "__")
    text = re.sub(r"[^0-9A-Za-z._-]+", "_", text)
    return text.strip("._") or "entity"


def render_card(conn: sqlite3.Connection, entity: sqlite3.Row, registry: CardRegistry | None = None) -> str:
    registry = registry or get_default_card_registry()
    type_name = entity["type"]
    hidden_ids = hidden_entity_ids(conn)
    location_id = redact_hidden_refs(entity["location_id"] or "无", hidden_ids) or "无"
    owner_id = redact_hidden_refs(entity["owner_id"] or "无", hidden_ids) or "无"
    details = redact_hidden_refs(parse_json(entity["details_json"], {}), hidden_ids)
    aliases = get_aliases(conn, entity["id"])
    lines = [
        GENERATED_MARKER,
        f"# {entity['id']} · {entity['name']}",
        "",
        "| 字段 | 值 |",
        "|------|----|",
        f"| 类型 | {display_label('entity_type', type_name)} |",
        f"| 状态 | {display_label('status', entity['status'])} |",
        f"| 可见性 | {display_label('visibility', entity['visibility'])} |",
        f"| 位置 | {location_id} |",
        f"| 所有者 | {owner_id} |",
        f"| 更新回合 | {entity['updated_turn_id']} |",
    ]
    if aliases:
        lines.append(f"| 别名 | {'；'.join(aliases)} |")
    summary = redact_hidden_refs(entity["summary"] or "无", hidden_ids) or "无"
    lines.extend(["", "## 快速摘要", shorten(summary, 420)])

    spec = registry.by_entity_type(str(type_name))
    if spec and spec.append_sections:
        spec.append_sections(conn, lines, entity)
    else:
        append_details_card(lines, details)

    append_active_facts(conn, lines, entity["id"])
    lines.extend(
        [
            "",
            "## 查询提示",
            "- 查询这个对象时优先读本卡，再按需查 SQLite。",
            "- 行动回合若改变本对象，必须写入结构化 delta 并重新生成卡片。",
        ]
    )
    return str(redact_hidden_refs("\n".join(lines), hidden_ids))


def append_item_card(conn: sqlite3.Connection, lines: list[str], entity: sqlite3.Row) -> None:
    item = conn.execute("select * from items where entity_id = ?", (entity["id"],)).fetchone()
    hidden_ids = hidden_entity_ids(conn)
    details = redact_hidden_refs(parse_json(entity["details_json"], {}), hidden_ids)
    properties = redact_hidden_refs(parse_json(item["properties_json"], {}) if item else {}, hidden_ids)
    if item:
        durability = "不适用"
        if item["durability_current"] is not None or item["durability_max"] is not None:
            durability = f"{item['durability_current'] or '?'} / {item['durability_max'] or '?'}"
        lines.extend(
            [
                "",
                "## 物品属性",
                "| 字段 | 值 |",
                "|------|----|",
                f"| 分类 | {display_label('item_category', item['category'])} |",
                f"| 数量 | {format_quantity(item)} |",
                f"| 品质 | {display_label('quality', item['quality'], default='未知')} |",
                f"| 耐久 | {durability} |",
                f"| 装备槽 | {item['equipped_slot'] or '无'} |",
                f"| 可堆叠 | {'是' if item['stackable'] else '否'} |",
            ]
        )
    append_item_profile_sections(lines, properties, heading_level=2)
    append_mapping(
        lines,
        "## 关键属性",
        properties,
        exclude={"combat_profile", "ammo_profile", "melee_profile", "defense_profile", "carry_profile"},
    )
    append_details_card(lines, details, exclude={"properties"})


def append_character_card(conn: sqlite3.Connection, lines: list[str], entity: sqlite3.Row) -> None:
    char = conn.execute("select * from characters where entity_id = ?", (entity["id"],)).fetchone()
    hidden_ids = hidden_entity_ids(conn)
    details = redact_hidden_refs(parse_json(entity["details_json"], {}), hidden_ids)
    profile = details.get("profile")
    if char:
        species_id = redact_hidden_refs(char["species_id"] or "未知", hidden_ids) or "未知"
        lines.extend(
            [
                "",
                "## 角色状态",
                "| 字段 | 值 |",
                "|------|----|",
                f"| 种族 | {species_id} |",
                f"| 角色定位 | {format_value(char['role']) if char['role'] else '未知'} |",
                f"| 态度 | {format_value(char['attitude']) if char['attitude'] else '未知'} |",
                f"| 信任 | {char['trust']} |",
                f"| 健康 | {format_value(char['health_state']) if char['health_state'] else '未知'} |",
            ]
        )
        append_mapping(lines, "## 压力", redact_hidden_refs(parse_json(char["stress_json"], {}), hidden_ids), exclude=set())
        append_sequence(lines, "## 长期后果", redact_hidden_refs(parse_json(char["consequences_json"], []), hidden_ids))
        append_sequence(lines, "## 目标", redact_hidden_refs(parse_json(char["goals_json"], []), hidden_ids))
    if isinstance(profile, dict):
        selected_profile = {key: profile[key] for key in CHARACTER_PROFILE_KEYS if key in profile}
        append_mapping(lines, "## 人物资料", selected_profile, exclude=set())
        omitted = len([key for key in profile if key not in selected_profile])
        if omitted:
            lines.append(f"- 另有 {omitted} 项低频资料留在 SQLite/source archive，需要时再查。")
    append_sequence(lines, "## 已知能力", details.get("known_abilities", []))
    append_sequence(lines, "## 当前承诺", details.get("commitments", []))
    append_sequence(lines, "## 未确认信息", details.get("unknowns", []))
    append_details_card(
        lines,
        details,
        exclude={"known_abilities", "commitments", "unknowns", "profile", "profile_excerpt"},
    )


def append_location_card(conn: sqlite3.Connection, lines: list[str], entity: sqlite3.Row) -> None:
    location = conn.execute("select * from locations where entity_id = ?", (entity["id"],)).fetchone()
    if not location:
        return
    hidden_ids = hidden_entity_ids(conn)
    parent_id = redact_hidden_refs(location["parent_id"] or "无", hidden_ids) or "无"
    exits = redact_hidden_refs(parse_json(location["exits_json"], []), hidden_ids)
    resources = redact_hidden_refs(parse_json(location["resources_json"], []), hidden_ids)
    lines.extend(
        [
            "",
            "## 地点属性",
            "| 字段 | 值 |",
            "|------|----|",
            f"| 父地点 | {parent_id} |",
            f"| 生态 | {display_label('biome', location['biome'], default='未知')} |",
            f"| 安全等级 | {display_label('safety_level', location['safety_level'], default='未知')} |",
            f"| 距家耗时 | {location['travel_minutes_from_home'] if location['travel_minutes_from_home'] is not None else '未知'} 分钟 |",
            f"| 坐标 | {format_coords(location)} |",
            f"| 发现回合 | {location['discovered_turn_id'] or '未知'} |",
            "",
            "## 地点描述",
            redact_hidden_refs(location["description_short"] or entity["summary"] or "无", hidden_ids) or "无",
        ]
    )
    append_sequence(lines, "## 已知资源", resources)
    append_sequence(lines, "## 出口/路线", exits)
    append_route_table(conn, lines, entity["id"])


def append_route_table(conn: sqlite3.Connection, lines: list[str], location_id: str) -> None:
    ensure_visibility_sql_functions(conn)
    target_visibility_clause = entity_visibility_sql(PLAYER_VIEW, "target")
    source_visibility_clause = entity_visibility_sql(PLAYER_VIEW, "source")
    target_subtype_clause = entity_subtype_visibility_sql(PLAYER_VIEW, "target", "target_clock")
    source_subtype_clause = entity_subtype_visibility_sql(PLAYER_VIEW, "source", "source_clock")
    routes = conn.execute(
        f"""
        select r.*, target.name as target_name
        from routes r
        join entities target on target.id = r.to_location_id
        left join clocks target_clock on target_clock.entity_id = target.id
        where r.from_location_id = ?
          and {normalized_text_sql("target.type")} = 'location'
          and {entity_not_archived_sql("target")}
          {target_visibility_clause}
          {target_subtype_clause}
        union all
        select r.*, source.name as target_name
        from routes r
        join entities source on source.id = r.from_location_id
        left join clocks source_clock on source_clock.entity_id = source.id
        where r.to_location_id = ?
          and {normalized_text_sql("source.type")} = 'location'
          and {entity_not_archived_sql("source")}
          {source_visibility_clause}
          {source_subtype_clause}
        order by travel_minutes, target_name
        """,
        (location_id, location_id),
    ).fetchall()
    if not routes:
        return
    lines.extend(["", "## 结构化路线", "| 方向 | 地点 | 耗时 | 难度 | 危险 | 需求 |", "|------|------|------|------|------|------|"])
    for route in routes:
        if route["from_location_id"] == location_id:
            direction = "去"
            other_id = route["to_location_id"]
        else:
            direction = "返"
            other_id = route["from_location_id"]
        hidden_ids = hidden_entity_ids(conn)
        hazards = redact_hidden_refs(parse_json(route["hazards_json"], []), hidden_ids)
        requirements = redact_hidden_refs(parse_json(route["requirements_json"], []), hidden_ids)
        lines.append(
            f"| {direction} | `{other_id}` {route['target_name']} | "
            f"{route['travel_minutes']}分钟 | {format_value(route['difficulty'])} | "
            f"{format_value(hazards)} | {format_value(requirements)} |"
        )


def append_clock_card(conn: sqlite3.Connection, lines: list[str], entity: sqlite3.Row) -> None:
    clock = conn.execute("select * from clocks where entity_id = ?", (entity["id"],)).fetchone()
    if not clock:
        return
    hidden_ids = hidden_entity_ids(conn)
    filled = int(clock["segments_filled"])
    total = int(clock["segments_total"])
    bar = "■" * filled + "□" * max(total - filled, 0)
    trigger = redact_hidden_refs(clock["trigger_when_full"] or "", hidden_ids) or ""
    lines.extend(
        [
            "",
            "## 进度钟",
            "| 字段 | 值 |",
            "|------|----|",
            f"| 类型 | {display_label('clock_type', clock['clock_type'])} |",
            f"| 进度 | {bar} {filled}/{total} |",
            f"| 可见性 | {display_label('visibility', clock['visibility'])} |",
            f"| 满格触发 | {trigger} |",
            f"| 上次推进 | {clock['last_ticked_turn_id'] or '未知'} |",
        ]
    )
    append_mapping(lines, "## 推进规则", redact_hidden_refs(parse_json(clock["tick_rules_json"], {}), hidden_ids), exclude=set())


def append_rule_card(conn: sqlite3.Connection, lines: list[str], entity: sqlite3.Row) -> None:
    rule = conn.execute("select * from rules where entity_id = ?", (entity["id"],)).fetchone()
    if not rule:
        return
    lines.extend(
        [
            "",
            "## 规则",
            "| 字段 | 值 |",
            "|------|----|",
            f"| 分类 | {display_label('rule_category', rule['category'])} |",
            f"| 范围 | {display_label('scope', rule['scope'])} |",
            f"| 锁定 | {'是' if rule['locked'] else '否'} |",
            f"| 来源 | {rule['source']} |",
            "",
            "## 规则文本",
            rule["statement"],
        ]
    )
    hidden_ids = hidden_entity_ids(conn)
    append_sequence(lines, "## 例子", redact_hidden_refs(parse_json(rule["examples_json"], []), hidden_ids))
    append_sequence(lines, "## 例外", redact_hidden_refs(parse_json(rule["exceptions_json"], []), hidden_ids))


def append_crop_plot_card(conn: sqlite3.Connection, lines: list[str], entity: sqlite3.Row) -> None:
    plot = conn.execute("select * from crop_plots where entity_id = ?", (entity["id"],)).fetchone()
    if not plot:
        return
    hidden_ids = hidden_entity_ids(conn)
    crop_entity_id = str(plot["crop_entity_id"])
    crop_display = "[hidden]" if crop_entity_id in hidden_ids else crop_entity_id
    expected_yield = redact_hidden_refs(plot["expected_yield"] or "未知", hidden_ids) or "未知"
    notes = redact_hidden_refs(plot["notes"] or "无", hidden_ids) or "无"
    lines.extend(
        [
            "",
            "## 农田",
            "| 字段 | 值 |",
            "|------|----|",
            f"| 畦号 | {plot['plot_no']} |",
            f"| 作物 | {crop_display} |",
            f"| 面积 | {plot['area_sqm'] if plot['area_sqm'] is not None else '未知'} 平方米 |",
            f"| 种植日 | {plot['planted_day'] if plot['planted_day'] is not None else '未知'} |",
            f"| 生长阶段 | {plot['growth_stage'] if plot['growth_stage'] is not None else '?'} / {plot['growth_stage_max'] if plot['growth_stage_max'] is not None else '?'} |",
            f"| 最早收获 | 第{plot['harvest_day_min']}天 |" if plot["harvest_day_min"] is not None else "| 最早收获 | 未知 |",
            f"| 最晚收获 | 第{plot['harvest_day_max']}天 |" if plot["harvest_day_max"] is not None else "| 最晚收获 | 未知 |",
            f"| 收获状态 | {display_label('crop_status', plot['harvest_status'], default='未知')} |",
            f"| 水分状态 | {display_label('water_status', plot['water_status'], default='未知')} |",
            f"| 土壤状态 | {display_label('soil_status', plot['soil_status'], default='未知')} |",
            f"| 预计产量 | {expected_yield} |",
            f"| 备注 | {notes} |",
        ]
    )


def append_knowledge_card(lines: list[str], details: dict[str, Any]) -> None:
    profile = details.get("encyclopedia") or details.get("profile")
    if isinstance(profile, dict):
        append_mapping(lines, "## 结构化资料", profile, exclude=set())
    excerpt = details.get("encyclopedia_excerpt") or details.get("profile_excerpt") or details.get("excerpt")
    if excerpt:
        lines.extend(["", "## 摘录", shorten(format_value(excerpt), 700)])
    append_details_card(
        lines,
        details,
        exclude={"encyclopedia", "profile", "encyclopedia_excerpt", "profile_excerpt", "excerpt"},
    )


def append_details_card(lines: list[str], details: dict[str, Any], exclude: set[str] | None = None) -> None:
    append_mapping(lines, "## 细节", details, exclude=exclude or set())


def append_mapping(lines: list[str], title: str, values: dict[str, Any], *, exclude: set[str]) -> None:
    items = [(key, value) for key, value in values.items() if key not in exclude and value not in (None, "", [], {})]
    if not items:
        return
    lines.extend(["", title])
    for key, value in items[:24]:
        lines.append(f"- {display_key(key)}: {shorten(format_value(value), 360)}")
    if len(items) > 24:
        lines.append(f"- 另有 {len(items) - 24} 项细节已省略；需要时查 SQLite。")


def append_sequence(lines: list[str], title: str, values: Any) -> None:
    if not values:
        return
    if not isinstance(values, list):
        values = [values]
    lines.extend(["", title])
    for value in values[:24]:
        lines.append(f"- {shorten(format_value(value), 360)}")
    if len(values) > 24:
        lines.append(f"- 另有 {len(values) - 24} 项已省略；需要时查 SQLite。")


def append_active_facts(conn: sqlite3.Connection, lines: list[str], entity_id: str) -> None:
    hidden_ids = hidden_entity_ids(conn)
    facts = conn.execute(
        """
        select predicate, object_entity_id, object_value, value_type, confidence, note
        from facts
        where subject_id = ? and valid_to_turn is null
        order by predicate
        limit 20
        """,
        (entity_id,),
    ).fetchall()
    if not facts:
        return
    lines.extend(["", "## 明确事实", "| 谓词 | 值 | 置信度 | 备注 |", "|------|----|--------|------|"])
    for fact in facts:
        value = fact["object_entity_id"] or fact["object_value"] or ""
        value = redact_hidden_refs(value, hidden_ids) or ""
        note = redact_hidden_refs(fact["note"] or "", hidden_ids) or ""
        lines.append(
            f"| {display_key(fact['predicate'])} | {format_value(value)} ({display_label('entity_type', fact['value_type'])}) | "
            f"{format_value(fact['confidence'])} | {note} |"
        )


def render_card_index(
    campaign: Campaign,
    conn: sqlite3.Connection,
    entities: list[sqlite3.Row],
    *,
    view: str = PLAYER_VIEW,
    registry: CardRegistry | None = None,
) -> str:
    view = normalize_visibility_view(view)
    registry = registry or get_default_card_registry()
    ensure_visibility_sql_functions(conn)
    meta = get_meta(conn)
    visible_entities = sorted(
        [row for row in entities if read_entity(conn, str(row["id"]), view=view)],
        key=lambda row: card_sort_key(row, registry),
    )
    counts: dict[str, int] = {}
    for row in visible_entities:
        counts[str(row["type"])] = counts.get(str(row["type"]), 0) + 1
    current_location_id = meta.get("current_location_id", "")
    entity_visibility_clause = entity_visibility_sql(view, "e")
    subtype_visibility_clause = entity_subtype_visibility_sql(view, "e", "c")
    current_location = conn.execute(
        f"""
        select e.name
        from entities e
        left join clocks c on c.entity_id = e.id
        where e.id = ?
          and {normalized_text_sql("e.type")} = 'location'
          and {entity_not_archived_sql("e")}
          {entity_visibility_clause}
          {subtype_visibility_clause}
        """,
        (current_location_id,),
    ).fetchone()
    player_entity_id = get_player_entity_id(conn)
    carried = conn.execute(
        f"""
        select e.*
        from entities e
        join items i on i.entity_id = e.id
        left join clocks c on c.entity_id = e.id
        where e.owner_id = ? and {normalized_text_sql("e.status")} = 'active'
          {entity_visibility_clause}
          {subtype_visibility_clause}
        order by i.equipped_slot is null, i.equipped_slot, e.name
        limit 20
        """,
        (player_entity_id,),
    ).fetchall()
    clock_visibility_clause = clock_visibility_sql(view, "c")
    clocks = conn.execute(
        f"""
        select e.*, c.segments_filled, c.segments_total, c.visibility as clock_visibility
        from entities e
        join clocks c on c.entity_id = e.id
        where {entity_not_archived_sql("e")}
          {clock_visibility_clause}
          {entity_visibility_clause}
          {subtype_visibility_clause}
        order by c.visibility, e.name
        """
    ).fetchall()

    lines = [
        GENERATED_MARKER,
        f"# {campaign.name} 资料卡索引",
        "",
        "| 字段 | 值 |",
        "|------|----|",
        f"| 当前回合 | {meta.get('current_turn_id', 'unknown')} |",
        f"| 游戏时间 | {format_time_brief(meta)} |",
        f"| 天气 | {format_weather_brief(meta)} |",
        f"| 索引视角 | {display_label('view', view)} |",
        f"| 当前位置 | {card_link(current_location_id, current_location['name'], 'location') if current_location else '当前地点不可见或不存在'} |",
        "",
        "## 实体统计",
        "| 类型 | 数量 |",
        "|------|------|",
    ]
    for entity_type in ordered_entity_types(counts.keys(), registry):
        lines.append(f"| {display_label('entity_type', entity_type)} | {counts[entity_type]} |")

    lines.extend(["", "## 当前随身重点"])
    if carried:
        for row in carried:
            lines.append(f"- {card_link(row['id'], row['name'], row['type'])} `{display_label('entity_type', row['type'])}`")
    else:
        lines.append("- 无")

    lines.extend(["", "## 活跃进度钟"])
    if clocks:
        for row in clocks:
            filled = int(row["segments_filled"])
            total = int(row["segments_total"])
            bar = "■" * filled + "□" * max(total - filled, 0)
            lines.append(
                f"- {card_link(row['id'], row['name'], row['type'])}: "
                f"{bar} {filled}/{total} `{display_label('visibility', row['clock_visibility'])}`"
            )
    else:
        lines.append("- 无")

    by_type: dict[str, list[sqlite3.Row]] = {}
    for row in visible_entities:
        by_type.setdefault(row["type"], []).append(row)
    for entity_type in ordered_entity_types(by_type.keys(), registry):
        spec = registry.by_entity_type(entity_type)
        title = spec.title if spec and spec.index_title else display_label("entity_type", entity_type)
        lines.extend(["", f"## {title}"])
        for row in by_type[entity_type]:
            summary = shorten(redact_hidden_refs(row["summary"] or "", hidden_entity_ids(conn)) or "", 110)
            suffix = f" - {summary}" if summary else ""
            lines.append(f"- {card_link(row['id'], row['name'], row['type'])}{suffix}")

    lines.extend(
        [
            "",
            "## 使用规则",
            "- 新会话优先读 `snapshots/current.md`、本索引和相关实体卡。",
            "- 查询类输入不推进时间；行动类输入必须写结构化 delta 并重新生成快照和卡片。",
            "- 卡片是快速上下文，权威事实仍以 `data/game.sqlite` 为准。",
        ]
    )
    text = "\n".join(lines)
    if view == PLAYER_VIEW:
        return str(redact_hidden_refs(text, hidden_entity_ids(conn)))
    return text


def ordered_entity_types(entity_types: Any, registry: CardRegistry | None = None) -> list[str]:
    registry = registry or get_default_card_registry()
    return sorted([str(entity_type) for entity_type in entity_types], key=lambda entity_type: registry.sort_key(entity_type, ""))


def card_link(entity_id: str, name: str, entity_type: str | None = None, registry: CardRegistry | None = None) -> str:
    registry = registry or get_default_card_registry()
    directory = card_directory(entity_type or entity_type_from_id(entity_id, registry), registry)
    path = Path(directory) / f"{safe_filename(entity_id)}.md"
    return f"[{name}]({path.as_posix()})"


def entity_type_from_id(entity_id: str, registry: CardRegistry | None = None) -> str:
    registry = registry or get_default_card_registry()
    return registry.entity_type_from_id(entity_id)


def get_aliases(conn: sqlite3.Connection, entity_id: str) -> list[str]:
    return [
        row["alias"]
        for row in conn.execute(
            "select alias from aliases where entity_id = ? order by alias",
            (entity_id,),
        ).fetchall()
    ]


def hidden_entity_ids(conn: sqlite3.Connection) -> set[str]:
    refs = hidden_entity_refs(conn)
    return {token for values in refs.values() for token in values}


def redact_hidden_refs(value: Any, hidden_ids: set[str]) -> Any:
    return redact_entity_refs(value, hidden_ids)


def format_coords(location: sqlite3.Row) -> str:
    coords = [location["coord_x"], location["coord_y"], location["coord_z"]]
    if all(value is None for value in coords):
        return "未知"
    return ", ".join("?" if value is None else str(value) for value in coords)


def shorten(text: str, limit: int) -> str:
    compact = " ".join(str(text).split())
    if len(compact) <= limit:
        return compact
    return compact[: max(limit - 1, 0)].rstrip() + "…"
