from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Any


CANONICAL_TAXONOMY_CATEGORIES = (
    "player-safe",
    "trusted low-level",
    "maintenance/admin",
    "platform sidecar",
    "platform prewarm",
    "projection/outbox",
)

PLAYER_SAFE_BYPASSES = (
    "direct GMRuntime.commit_turn",
    "raw delta or TurnProposal exposure",
    "hidden/GM-only access",
    "profile escalation",
)
TRUSTED_LOW_LEVEL_BYPASSES = (
    "default player profile exposure",
    "commit without validation",
    "hidden access without trusted profile",
)
MAINTENANCE_BYPASSES = (
    "normal player profile exposure",
    "unvalidated save mutation",
    "workspace root escape",
)
PLATFORM_SIDECAR_BYPASSES = (
    "direct gameplay fact write",
    "session or actor gate bypass",
    "business logic reimplementation outside SaveManager",
)
PLATFORM_PREWARM_BYPASSES = (
    "turn preview",
    "validation or commit",
    "permission or proposal caching",
)
PROJECTION_BYPASSES = (
    "fact authority",
    "pre-commit write",
    "rollback policy",
)
PROMPT_BYPASSES = (
    "permission grant",
    "save authorization",
    "hidden access",
)
AUTHORITY_GATE_REQUIRED_WRITE_MODE_TOKENS = (
    "admin",
    "advisory",
    "binding",
    "commit",
    "controlled_import",
    "dispatch",
    "gate",
    "maintenance",
    "outbox",
    "projection",
    "serve_or_config",
)
NON_SURFACE_PUBLIC_APIS = {
    "GMRuntime": {
        "action_from_delta": "Pure helper that maps an already validated delta to an action id.",
        "action_options_from_delta": "Pure helper that extracts action options from an already validated delta.",
        "capability_error_for_action": "Internal capability helper used by runtime entrypoints.",
        "capability_errors_for_delta": "Internal capability helper used by runtime entrypoints.",
        "capability_for_action": "Internal action registry lookup helper.",
        "declared_capabilities": "Internal capability reporting helper.",
        "effective_action_options": "Internal option normalization helper used before preview/validation.",
        "health": "Read-only runtime diagnostic reached through MCP/CLI health surfaces.",
        "preview_intent": "Internal helper reached through preview_from_text after intent routing.",
        "require_capability": "Internal guard helper used by runtime entrypoints.",
        "supports_capability": "Internal capability predicate.",
        "ux_metrics": "Read-only runtime diagnostic reached through CLI ux-metrics surface.",
    },
    "PlatformSidecar": {
        "activate_from_result": "Internal binding-state helper called after platform entrypoints return.",
        "drain_prewarm": "Diagnostic queue drain helper behind platform message --drain.",
        "gate_player_entry": "Internal platform gate helper used by act/confirm entrypoints.",
        "start": "Sidecar lifecycle helper, not a gameplay or player entry surface.",
        "stop": "Sidecar lifecycle helper, not a gameplay or player entry surface.",
    },
    "projections": {
        "ensure_projection_rows": "Internal projection table setup helper.",
        "mark_projection_clean": "Internal projection state update helper.",
        "mark_projection_failed": "Internal projection state update helper.",
        "mark_projections_clean": "Internal projection state update helper.",
        "mark_projections_dirty": "Internal projection state update helper.",
        "projection_effective_status": "Internal status calculation helper.",
        "projection_tables_exist": "Internal projection schema predicate.",
    },
}


@dataclass(frozen=True)
class SurfaceEntry:
    name: str
    surface: str
    category: str
    profile: str
    write_mode: str
    default_exposed: bool
    normal_play: bool
    description: str
    notes: tuple[str, ...] = ()
    related_tools: tuple[str, ...] = ()
    taxonomy_category: str = ""
    write_authority: str = ""
    intended_caller: str = ""
    forbidden_bypasses: tuple[str, ...] = ()
    authority_gate: str = ""

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


FORBIDDEN_DEFAULT_MCP_TOKENS = (
    "admin",
    "repair",
    "migration",
    "migrate",
    "plugin",
    "upgrade",
    "reconcile",
    "install",
    "import",
    "export",
    "patch",
    "backup",
    "restore",
    "arbitrary_file",
)


MCP_SURFACE_INVENTORY = (
    SurfaceEntry(
        name="workspace_inspect",
        surface="mcp",
        category="workspace_registry",
        taxonomy_category="player-safe",
        profile="player_read",
        write_mode="read_only",
        write_authority="read workspace registry metadata only",
        intended_caller="player MCP profile",
        default_exposed=True,
        normal_play=True,
        description="Inspect the configured player workspace registry.",
        forbidden_bypasses=PLAYER_SAFE_BYPASSES,
    ),
    SurfaceEntry(
        name="campaign_list",
        surface="mcp",
        category="campaign_package",
        taxonomy_category="player-safe",
        profile="player_read",
        write_mode="read_only",
        write_authority="read registered player-facing campaign packages",
        intended_caller="player MCP profile",
        default_exposed=True,
        normal_play=True,
        description="List player-facing campaign packages registered under the MCP root.",
        forbidden_bypasses=PLAYER_SAFE_BYPASSES,
    ),
    SurfaceEntry(
        name="save_list",
        surface="mcp",
        category="save_package",
        taxonomy_category="player-safe",
        profile="player_read",
        write_mode="read_only",
        write_authority="read registered player-facing saves",
        intended_caller="player MCP profile",
        default_exposed=True,
        normal_play=True,
        description="List player-facing saves registered under the MCP root.",
        forbidden_bypasses=PLAYER_SAFE_BYPASSES,
    ),
    SurfaceEntry(
        name="save_current",
        surface="mcp",
        category="save_package",
        taxonomy_category="player-safe",
        profile="player_read",
        write_mode="read_only",
        write_authority="read active save registry selection",
        intended_caller="player MCP profile",
        default_exposed=True,
        normal_play=True,
        description="Return the active player-facing save.",
        forbidden_bypasses=PLAYER_SAFE_BYPASSES,
    ),
    SurfaceEntry(
        name="save_create",
        surface="mcp",
        category="save_package",
        taxonomy_category="player-safe",
        profile="player_controlled_create",
        write_mode="controlled_create",
        write_authority="create save package workspace state without committing gameplay facts",
        intended_caller="player MCP profile",
        default_exposed=True,
        normal_play=True,
        description="Create a new save package from a campaign or starter save.",
        notes=("May create save files, but must not advance story facts or mutate gameplay state.",),
        forbidden_bypasses=PLAYER_SAFE_BYPASSES,
    ),
    SurfaceEntry(
        name="save_switch",
        surface="mcp",
        category="save_package",
        taxonomy_category="player-safe",
        profile="player_controlled_selection",
        write_mode="controlled_selection",
        write_authority="switch active save registry selection only",
        intended_caller="player MCP profile",
        default_exposed=True,
        normal_play=True,
        description="Switch the active player-facing save.",
        notes=("Selects a save registry entry; does not change story facts.",),
        forbidden_bypasses=PLAYER_SAFE_BYPASSES,
    ),
    SurfaceEntry(
        name="start_or_continue",
        surface="mcp",
        category="player_entry",
        taxonomy_category="player-safe",
        profile="player_controlled_create",
        write_mode="controlled_create",
        write_authority="start or create a save, then return player-safe onboarding context",
        intended_caller="player MCP profile",
        default_exposed=True,
        normal_play=True,
        description="Continue an active save, or create one and return onboarding context.",
        notes=("May create a save package for onboarding; gameplay facts still require player_turn/player_confirm.",),
        forbidden_bypasses=PLAYER_SAFE_BYPASSES,
    ),
    SurfaceEntry(
        name="intent_manifest",
        surface="mcp",
        category="player_contract",
        taxonomy_category="player-safe",
        profile="player_read",
        write_mode="read_only",
        write_authority="read kernel-generated intent/action contract only",
        intended_caller="player MCP profile and external AI client",
        default_exposed=True,
        normal_play=True,
        description="Read-only kernel-generated action/query manifest for external candidate construction.",
        notes=("Contract source only; natural-language play still enters player_turn.",),
        related_tools=("player_turn",),
        forbidden_bypasses=PLAYER_SAFE_BYPASSES,
    ),
    SurfaceEntry(
        name="player_query",
        surface="mcp",
        category="player_workflow",
        taxonomy_category="trusted low-level",
        profile="player_turn_read",
        write_mode="read_only",
        write_authority="read active save through compatibility query path",
        intended_caller="developer or trusted compatibility client",
        default_exposed=False,
        normal_play=False,
        description="Structured compatibility query against the active save; normal natural language enters player_turn.",
        forbidden_bypasses=TRUSTED_LOW_LEVEL_BYPASSES,
        authority_gate="MCP profile gate; default player profile excludes this compatibility tool.",
    ),
    SurfaceEntry(
        name="player_turn",
        surface="mcp",
        category="player_workflow",
        taxonomy_category="player-safe",
        profile="player_turn_preview",
        write_mode="preview_only",
        write_authority="create pending player action or clarification runtime state only",
        intended_caller="player MCP profile",
        default_exposed=True,
        normal_play=True,
        description="Standard player turn entry for natural-language query/action/clarify/block without exposing delta or TurnProposal JSON.",
        related_tools=("player_confirm",),
        forbidden_bypasses=PLAYER_SAFE_BYPASSES,
    ),
    SurfaceEntry(
        name="player_act",
        surface="mcp",
        category="player_workflow",
        taxonomy_category="trusted low-level",
        profile="player_turn_preview",
        write_mode="preview_only",
        write_authority="compatibility preview wrapper; no gameplay fact commit",
        intended_caller="developer or trusted compatibility client",
        default_exposed=False,
        normal_play=False,
        description="Compatibility player action preview; new normal play uses player_turn.",
        related_tools=("player_confirm",),
        forbidden_bypasses=TRUSTED_LOW_LEVEL_BYPASSES,
        authority_gate="MCP profile gate; default player profile uses player_turn instead.",
    ),
    SurfaceEntry(
        name="player_confirm",
        surface="mcp",
        category="player_workflow",
        taxonomy_category="player-safe",
        profile="player_turn_commit",
        write_mode="validated_commit",
        write_authority="commit only the matching pending player_turn action through SaveManager.player_confirm",
        intended_caller="player MCP profile",
        default_exposed=True,
        normal_play=True,
        description="Confirm and save the pending player action using the player_turn session_id without exposing delta or TurnProposal JSON.",
        related_tools=("player_turn", "player_act"),
        forbidden_bypasses=PLAYER_SAFE_BYPASSES,
        authority_gate="Requires matching pending action session_id, active save, expiry, and optional platform identity.",
    ),
    SurfaceEntry(
        name="campaign_validate",
        surface="mcp",
        category="campaign_package",
        taxonomy_category="player-safe",
        profile="player_read",
        write_mode="read_only",
        write_authority="validate campaign package without mutating it",
        intended_caller="player MCP profile",
        default_exposed=True,
        normal_play=True,
        description="Validate a configured campaign package without mutating it.",
        forbidden_bypasses=PLAYER_SAFE_BYPASSES,
    ),
    SurfaceEntry(
        name="save_inspect",
        surface="mcp",
        category="save_package",
        taxonomy_category="player-safe",
        profile="player_read",
        write_mode="read_only",
        write_authority="inspect save package without mutating gameplay facts",
        intended_caller="player MCP profile",
        default_exposed=True,
        normal_play=True,
        description="Inspect a configured save package without mutating it.",
        forbidden_bypasses=PLAYER_SAFE_BYPASSES,
    ),
    SurfaceEntry(
        name="start_turn",
        surface="mcp",
        category="turn_workflow",
        taxonomy_category="trusted low-level",
        profile="player_turn_read",
        write_mode="read_only",
        write_authority="build low-level turn context and contract without committing facts",
        intended_caller="developer or trusted GM MCP profile",
        default_exposed=False,
        normal_play=False,
        description="Low-level context packet and turn contract builder for one player request.",
        forbidden_bypasses=TRUSTED_LOW_LEVEL_BYPASSES,
        authority_gate="MCP profile gate; ordinary play uses player_turn.",
    ),
    SurfaceEntry(
        name="intent_preflight",
        surface="mcp",
        category="turn_workflow",
        taxonomy_category="trusted low-level",
        profile="developer_or_trusted_gm_advisory_cache",
        write_mode="advisory_only",
        write_authority="create identity-bound single-use advisory preflight cache only",
        intended_caller="developer or trusted GM MCP profile",
        default_exposed=False,
        normal_play=False,
        description="Precompute an advisory internal intent review for later same-context reuse.",
        notes=("Does not preview, commit, or change gameplay facts; stores only advisory cache state.",),
        related_tools=("preview_from_text",),
        forbidden_bypasses=TRUSTED_LOW_LEVEL_BYPASSES,
        authority_gate="MCP profile gate plus preflight identity/TTL/single-use checks.",
    ),
    SurfaceEntry(
        name="query",
        surface="mcp",
        category="turn_workflow",
        taxonomy_category="trusted low-level",
        profile="player_turn_read",
        write_mode="read_only",
        write_authority="low-level player-visible read without advancing time or saving facts",
        intended_caller="developer or trusted GM MCP profile",
        default_exposed=False,
        normal_play=False,
        description="Low-level read of current player-visible state without advancing time or saving facts.",
        forbidden_bypasses=TRUSTED_LOW_LEVEL_BYPASSES,
        authority_gate="MCP profile gate; ordinary play uses player_turn/query result families.",
    ),
    SurfaceEntry(
        name="preview_from_text",
        surface="mcp",
        category="turn_workflow",
        taxonomy_category="trusted low-level",
        profile="player_turn_preview",
        write_mode="preview_only",
        write_authority="low-level natural-language preview without commit",
        intended_caller="developer or trusted GM MCP profile",
        default_exposed=False,
        normal_play=False,
        description="Low-level natural-language preview primitive; player_turn is the normal play entry.",
        related_tools=("start_turn", "validate_delta", "commit_turn"),
        forbidden_bypasses=TRUSTED_LOW_LEVEL_BYPASSES,
        authority_gate="MCP profile gate; player profile uses player_turn.",
    ),
    SurfaceEntry(
        name="preview_action",
        surface="mcp",
        category="turn_low_level",
        taxonomy_category="trusted low-level",
        profile="developer_or_trusted_gm_low_level",
        write_mode="preview_only",
        write_authority="low-level action preview for an already-selected action contract",
        intended_caller="developer or trusted GM MCP profile",
        default_exposed=False,
        normal_play=False,
        description="Low-level preview for an already-selected action contract.",
        notes=("Default player profile is code-gated from this tool; use player_turn for normal play.",),
        related_tools=("preview_from_text",),
        forbidden_bypasses=TRUSTED_LOW_LEVEL_BYPASSES,
        authority_gate="MCP profile gate.",
    ),
    SurfaceEntry(
        name="validate_delta",
        surface="mcp",
        category="turn_low_level",
        taxonomy_category="trusted low-level",
        profile="developer_or_trusted_gm_validation",
        write_mode="validation_only",
        write_authority="validate structured delta without saving it",
        intended_caller="developer or trusted GM MCP profile",
        default_exposed=False,
        normal_play=False,
        description="Validate a structured turn delta without saving it.",
        forbidden_bypasses=TRUSTED_LOW_LEVEL_BYPASSES,
        authority_gate="MCP profile gate.",
    ),
    SurfaceEntry(
        name="commit_turn",
        surface="mcp",
        category="turn_low_level",
        taxonomy_category="trusted low-level",
        profile="developer_or_trusted_gm_commit",
        write_mode="validated_commit",
        write_authority="commit one validated and accepted TurnProposal delta to a configured save",
        intended_caller="developer or trusted GM MCP profile",
        default_exposed=False,
        normal_play=False,
        description="Commit one validated and accepted TurnProposal delta to a configured save.",
        notes=("Default player profile is code-gated from this tool; use player_confirm for normal play.",),
        forbidden_bypasses=TRUSTED_LOW_LEVEL_BYPASSES,
        authority_gate="MCP profile gate plus validation and accepted TurnProposal requirements.",
    ),
    SurfaceEntry(
        name="health",
        surface="mcp",
        category="runtime_health",
        taxonomy_category="player-safe",
        profile="player_read",
        write_mode="read_only",
        write_authority="read runtime health evidence only",
        intended_caller="player MCP profile",
        default_exposed=True,
        normal_play=True,
        description="Run a read-only health check for a configured save.",
        notes=("Does not run repair or projection rebuild.",),
        forbidden_bypasses=PLAYER_SAFE_BYPASSES,
    ),
)

AI_PROMPT_SURFACE_INVENTORY = (
    SurfaceEntry(
        name="docs/prompts/ai-client-prompt.md",
        surface="ai_prompt",
        category="external_ai_gm",
        taxonomy_category="player-safe",
        profile="external_agent_low_trust",
        write_mode="workflow_guidance_only",
        write_authority="instructions only; no engine permission or write grant",
        intended_caller="external AI client",
        default_exposed=True,
        normal_play=True,
        description="Generic external AI client prompt for MCP/CLI play.",
        notes=("Prompt guidance is not a permission grant.",),
        related_tools=("player_turn", "player_confirm", "start_turn", "preview_from_text", "validate_delta", "commit_turn"),
        forbidden_bypasses=PROMPT_BYPASSES,
    ),
    SurfaceEntry(
        name="docs/prompts/author-ai-prompt.md",
        surface="ai_prompt",
        category="campaign_authoring",
        taxonomy_category="maintenance/admin",
        profile="authoring_low_trust",
        write_mode="author_files_only",
        write_authority="guidance for campaign author files only",
        intended_caller="external authoring AI",
        default_exposed=False,
        normal_play=False,
        description="External AI prompt for campaign package authoring and doctor fixes.",
        notes=("Must not edit save packages, runtime databases, plugins, scripts or executable rules.",),
        forbidden_bypasses=PROMPT_BYPASSES,
    ),
    SurfaceEntry(
        name="campaign-local AUTHOR_AI_PROMPT.md",
        surface="ai_prompt",
        category="campaign_authoring",
        taxonomy_category="maintenance/admin",
        profile="authoring_low_trust",
        write_mode="author_files_only",
        write_authority="guidance for campaign-local author files only",
        intended_caller="external authoring AI",
        default_exposed=False,
        normal_play=False,
        description="Template-copied authoring prompt inside campaign packages.",
        notes=("Applies to campaign package source files, not save package state.",),
        forbidden_bypasses=PROMPT_BYPASSES,
    ),
)

CLI_V1_COMMAND_SURFACE_INVENTORY = (
    SurfaceEntry(
        name="aigm campaign",
        surface="cli_v1",
        category="command_group",
        taxonomy_category="maintenance/admin",
        profile="authoring_or_maintenance",
        write_mode="subcommand_dispatch",
        write_authority="dispatch campaign authoring and diagnostics subcommands only",
        intended_caller="local author or maintainer",
        default_exposed=False,
        normal_play=False,
        description="V1 campaign package command group.",
        forbidden_bypasses=MAINTENANCE_BYPASSES,
        authority_gate="campaign_type subcommand selects read/create/diagnostic authority.",
    ),
    SurfaceEntry(
        name="aigm save",
        surface="cli_v1",
        category="command_group",
        taxonomy_category="maintenance/admin",
        profile="player_or_maintenance",
        write_mode="subcommand_dispatch",
        write_authority="dispatch save inspect/create/import/export/patch subcommands",
        intended_caller="local player host or maintainer",
        default_exposed=False,
        normal_play=False,
        description="V1 save package command group.",
        forbidden_bypasses=MAINTENANCE_BYPASSES,
        authority_gate="save_type subcommand selects player-safe read/create or maintenance authority.",
    ),
    SurfaceEntry(
        name="aigm play",
        surface="cli_v1",
        category="command_group",
        taxonomy_category="trusted low-level",
        profile="developer_or_trusted_gm",
        write_mode="subcommand_dispatch",
        write_authority="dispatch low-level runtime preview, validation, and commit commands",
        intended_caller="developer or trusted local GM",
        default_exposed=False,
        normal_play=False,
        description="Developer/trusted low-level runtime command group.",
        forbidden_bypasses=TRUSTED_LOW_LEVEL_BYPASSES,
        authority_gate="play_type subcommand separates preflight/start/query/preview/validate/commit.",
    ),
    SurfaceEntry(
        name="aigm mcp",
        surface="cli_v1",
        category="command_group",
        taxonomy_category="trusted low-level",
        profile="mcp_host",
        write_mode="serve_or_config",
        write_authority="serve MCP tools according to configured MCP profile",
        intended_caller="local MCP host",
        default_exposed=False,
        normal_play=False,
        description="MCP adapter host/profile command group.",
        forbidden_bypasses=TRUSTED_LOW_LEVEL_BYPASSES,
        authority_gate="subcommand and --mcp-profile gate player-safe versus low-level tool exposure.",
    ),
    SurfaceEntry(
        name="aigm player",
        surface="cli_v1",
        category="command_group",
        taxonomy_category="player-safe",
        profile="player_cli",
        write_mode="player_workflow_dispatch",
        write_authority="dispatch player-safe registry, pending preview, and confirmation commands",
        intended_caller="local player host",
        default_exposed=True,
        normal_play=True,
        description="Player-safe save registry and turn command group.",
        forbidden_bypasses=PLAYER_SAFE_BYPASSES,
        authority_gate="player_type subcommand keeps ordinary writes behind player_turn/player_confirm.",
    ),
    SurfaceEntry(
        name="aigm platform",
        surface="cli_v1",
        category="command_group",
        taxonomy_category="platform sidecar",
        profile="platform_adapter",
        write_mode="gate_and_forward",
        write_authority="forward platform messages through PlatformSidecar and SaveManager gates",
        intended_caller="local platform adapter host",
        default_exposed=False,
        normal_play=False,
        description="Platform sidecar prewarm and player entry command group.",
        forbidden_bypasses=PLATFORM_SIDECAR_BYPASSES,
        authority_gate="platform_type subcommand plus platform/session/actor identity gate.",
    ),
    SurfaceEntry(
        name="aigm eval",
        surface="cli_v1",
        category="command_group",
        taxonomy_category="maintenance/admin",
        profile="developer_eval",
        write_mode="test_artifacts_only",
        write_authority="run deterministic evals against fixtures or temp campaign copies",
        intended_caller="developer or test maintainer",
        default_exposed=False,
        normal_play=False,
        description="Deterministic engine eval command group.",
        forbidden_bypasses=MAINTENANCE_BYPASSES,
        authority_gate="eval_type subcommand; should not mutate formal current saves.",
    ),
)


def _cli_v1_subcommand_entry(
    command: str,
    *,
    category: str,
    taxonomy_category: str,
    profile: str,
    write_mode: str,
    write_authority: str,
    intended_caller: str,
    description: str,
    forbidden_bypasses: tuple[str, ...],
    authority_gate: str = "",
    default_exposed: bool = False,
    normal_play: bool = False,
) -> SurfaceEntry:
    return SurfaceEntry(
        name=f"aigm {command}",
        surface="cli_v1",
        category=category,
        taxonomy_category=taxonomy_category,
        profile=profile,
        write_mode=write_mode,
        write_authority=write_authority,
        intended_caller=intended_caller,
        default_exposed=default_exposed,
        normal_play=normal_play,
        description=description,
        forbidden_bypasses=forbidden_bypasses,
        authority_gate=authority_gate,
    )


CLI_V1_SUBCOMMAND_SURFACE_INVENTORY = (
    _cli_v1_subcommand_entry(
        "campaign copy-example",
        category="campaign_package",
        taxonomy_category="maintenance/admin",
        profile="authoring",
        write_mode="controlled_create",
        write_authority="copy packaged campaign example files to an explicit target",
        intended_caller="campaign author",
        description="Copy a packaged example campaign.",
        forbidden_bypasses=MAINTENANCE_BYPASSES,
        authority_gate="Explicit target directory plus --force overwrite gate.",
    ),
    _cli_v1_subcommand_entry(
        "campaign outline",
        category="campaign_package",
        taxonomy_category="maintenance/admin",
        profile="authoring_read",
        write_mode="read_only",
        write_authority="render author-facing campaign outline only",
        intended_caller="campaign author",
        description="Render an author-facing campaign outline.",
        forbidden_bypasses=MAINTENANCE_BYPASSES,
    ),
    _cli_v1_subcommand_entry(
        "campaign explain",
        category="campaign_package",
        taxonomy_category="maintenance/admin",
        profile="authoring_read",
        write_mode="read_only",
        write_authority="explain authoring topics without mutating package or save state",
        intended_caller="campaign author",
        description="Explain an authoring field, capability, or error.",
        forbidden_bypasses=MAINTENANCE_BYPASSES,
    ),
    _cli_v1_subcommand_entry(
        "campaign check-ai",
        category="campaign_package",
        taxonomy_category="maintenance/admin",
        profile="authoring_read",
        write_mode="read_only",
        write_authority="check AI-assisted authoring issues without mutating state",
        intended_caller="campaign author",
        description="Check common AI-assisted authoring issues.",
        forbidden_bypasses=MAINTENANCE_BYPASSES,
    ),
    _cli_v1_subcommand_entry(
        "campaign split",
        category="campaign_package",
        taxonomy_category="maintenance/admin",
        profile="authoring_maintenance",
        write_mode="author_files_maintenance",
        write_authority="suggest or apply campaign source-file split only",
        intended_caller="campaign author",
        description="Suggest or apply a campaign content split plan.",
        forbidden_bypasses=MAINTENANCE_BYPASSES,
        authority_gate="Dry-run is read-only; --apply writes campaign author files only.",
    ),
    _cli_v1_subcommand_entry(
        "play preflight",
        category="turn_workflow",
        taxonomy_category="trusted low-level",
        profile="developer_or_trusted_gm_advisory_cache",
        write_mode="advisory_only",
        write_authority="create identity-bound advisory preflight cache only",
        intended_caller="developer or trusted local GM",
        description="Precompute advisory internal intent review from CLI.",
        forbidden_bypasses=TRUSTED_LOW_LEVEL_BYPASSES,
        authority_gate="preflight identity profile, TTL, text hash, and message/session binding.",
    ),
    _cli_v1_subcommand_entry(
        "play start-turn",
        category="turn_workflow",
        taxonomy_category="trusted low-level",
        profile="developer_or_trusted_gm_context",
        write_mode="read_only",
        write_authority="build low-level context and turn contract without committing facts",
        intended_caller="developer or trusted local GM",
        description="Build context and classify one player turn.",
        forbidden_bypasses=TRUSTED_LOW_LEVEL_BYPASSES,
    ),
    _cli_v1_subcommand_entry(
        "play query",
        category="turn_workflow",
        taxonomy_category="trusted low-level",
        profile="developer_or_trusted_gm_read",
        write_mode="read_only",
        write_authority="read runtime query output without advancing time or saving facts",
        intended_caller="developer or trusted local GM",
        description="Run a non-mutating runtime query.",
        forbidden_bypasses=TRUSTED_LOW_LEVEL_BYPASSES,
    ),
    _cli_v1_subcommand_entry(
        "play act",
        category="turn_workflow",
        taxonomy_category="trusted low-level",
        profile="developer_or_trusted_gm_preview",
        write_mode="preview_only",
        write_authority="low-level natural-language preview without ordinary player confirm",
        intended_caller="developer or trusted local GM",
        description="Interpret natural-language player action through the low-level runtime path.",
        forbidden_bypasses=TRUSTED_LOW_LEVEL_BYPASSES,
        authority_gate="Trusted CLI use; ordinary player path is aigm player turn/confirm.",
    ),
    _cli_v1_subcommand_entry(
        "play preview",
        category="turn_low_level",
        taxonomy_category="trusted low-level",
        profile="developer_or_trusted_gm_low_level",
        write_mode="preview_only",
        write_authority="preview an already-selected action contract without saving facts",
        intended_caller="developer or trusted local GM",
        description="Preview a selected action.",
        forbidden_bypasses=TRUSTED_LOW_LEVEL_BYPASSES,
    ),
    _cli_v1_subcommand_entry(
        "play validate-delta",
        category="turn_low_level",
        taxonomy_category="trusted low-level",
        profile="developer_or_trusted_gm_validation",
        write_mode="validation_only",
        write_authority="validate structured delta without saving it",
        intended_caller="developer or trusted local GM",
        description="Validate one turn delta through GMRuntime.",
        forbidden_bypasses=TRUSTED_LOW_LEVEL_BYPASSES,
    ),
    _cli_v1_subcommand_entry(
        "play commit",
        category="turn_low_level",
        taxonomy_category="trusted low-level",
        profile="developer_or_trusted_gm_commit",
        write_mode="validated_commit",
        write_authority="commit validated and accepted TurnProposal delta through GMRuntime",
        intended_caller="developer or trusted local GM",
        description="Commit one accepted low-level turn proposal.",
        forbidden_bypasses=TRUSTED_LOW_LEVEL_BYPASSES,
        authority_gate="Requires validation, accepted TurnProposal, backup/audit policy, and trusted caller.",
    ),
    _cli_v1_subcommand_entry(
        "play health",
        category="runtime_health",
        taxonomy_category="trusted low-level",
        profile="developer_or_trusted_gm_read",
        write_mode="read_only",
        write_authority="read runtime health evidence only",
        intended_caller="developer or trusted local GM",
        description="Run a read-only runtime health check.",
        forbidden_bypasses=TRUSTED_LOW_LEVEL_BYPASSES,
    ),
    _cli_v1_subcommand_entry(
        "play ux-metrics",
        category="runtime_health",
        taxonomy_category="trusted low-level",
        profile="developer_or_trusted_gm_read",
        write_mode="read_only",
        write_authority="read UX-oriented runtime metrics only",
        intended_caller="developer or trusted local GM",
        description="Render UX-oriented runtime metrics.",
        forbidden_bypasses=TRUSTED_LOW_LEVEL_BYPASSES,
    ),
    _cli_v1_subcommand_entry(
        "mcp serve",
        category="mcp_adapter",
        taxonomy_category="trusted low-level",
        profile="mcp_host",
        write_mode="serve_or_config",
        write_authority="serve MCP tools according to configured profile gates",
        intended_caller="local MCP host",
        description="Serve the V1 MCP adapter over stdio.",
        forbidden_bypasses=TRUSTED_LOW_LEVEL_BYPASSES,
        authority_gate="--mcp-profile selects player-safe versus low-level tool exposure.",
    ),
    _cli_v1_subcommand_entry(
        "mcp print-config",
        category="mcp_adapter",
        taxonomy_category="trusted low-level",
        profile="mcp_host",
        write_mode="read_only",
        write_authority="print MCP client configuration without starting tools or writing facts",
        intended_caller="local MCP host",
        description="Print AI client MCP JSON config.",
        forbidden_bypasses=TRUSTED_LOW_LEVEL_BYPASSES,
        authority_gate="--mcp-profile in generated config determines runtime tool exposure.",
    ),
    _cli_v1_subcommand_entry(
        "player inspect",
        category="player_registry",
        taxonomy_category="player-safe",
        profile="player_read",
        write_mode="read_only",
        write_authority="read player workspace registry metadata only",
        intended_caller="local player host",
        default_exposed=True,
        normal_play=True,
        description="Inspect a player workspace registry.",
        forbidden_bypasses=PLAYER_SAFE_BYPASSES,
    ),
    _cli_v1_subcommand_entry(
        "player campaigns",
        category="player_registry",
        taxonomy_category="player-safe",
        profile="player_read",
        write_mode="read_only",
        write_authority="list registered player-facing campaigns",
        intended_caller="local player host",
        default_exposed=True,
        normal_play=True,
        description="List registered campaigns.",
        forbidden_bypasses=PLAYER_SAFE_BYPASSES,
    ),
    _cli_v1_subcommand_entry(
        "player saves",
        category="player_registry",
        taxonomy_category="player-safe",
        profile="player_read",
        write_mode="read_only",
        write_authority="list registered player-facing saves",
        intended_caller="local player host",
        default_exposed=True,
        normal_play=True,
        description="List registered saves.",
        forbidden_bypasses=PLAYER_SAFE_BYPASSES,
    ),
    _cli_v1_subcommand_entry(
        "player current",
        category="player_registry",
        taxonomy_category="player-safe",
        profile="player_read",
        write_mode="read_only",
        write_authority="read active save registry selection only",
        intended_caller="local player host",
        default_exposed=True,
        normal_play=True,
        description="Show the active save.",
        forbidden_bypasses=PLAYER_SAFE_BYPASSES,
    ),
    _cli_v1_subcommand_entry(
        "player start",
        category="player_entry",
        taxonomy_category="player-safe",
        profile="player_controlled_create",
        write_mode="controlled_create",
        write_authority="continue or create active save without committing gameplay facts",
        intended_caller="local player host",
        default_exposed=True,
        normal_play=True,
        description="Continue active save or create one if missing.",
        forbidden_bypasses=PLAYER_SAFE_BYPASSES,
        authority_gate="SaveManager.start_or_continue handles active-save and create-if-missing gates.",
    ),
    _cli_v1_subcommand_entry(
        "player query",
        category="player_workflow",
        taxonomy_category="player-safe",
        profile="player_read",
        write_mode="read_only",
        write_authority="read player-visible query output without saving facts",
        intended_caller="local player host",
        default_exposed=True,
        normal_play=True,
        description="Ask a player-facing question about the active save.",
        forbidden_bypasses=PLAYER_SAFE_BYPASSES,
    ),
    _cli_v1_subcommand_entry(
        "player turn",
        category="player_workflow",
        taxonomy_category="player-safe",
        profile="player_turn_preview",
        write_mode="preview_only",
        write_authority="create pending player action or clarification runtime state only",
        intended_caller="local player host",
        default_exposed=True,
        normal_play=True,
        description="Standard natural-language player turn.",
        forbidden_bypasses=PLAYER_SAFE_BYPASSES,
        authority_gate="SaveManager.player_turn keeps facts pending until player confirm.",
    ),
    _cli_v1_subcommand_entry(
        "player act",
        category="player_workflow",
        taxonomy_category="player-safe",
        profile="player_turn_preview",
        write_mode="preview_only",
        write_authority="compatibility wrapper that creates pending action or clarification only",
        intended_caller="local player host",
        default_exposed=True,
        normal_play=True,
        description="Compatibility wrapper for natural-language player turns.",
        forbidden_bypasses=PLAYER_SAFE_BYPASSES,
        authority_gate="SaveManager.player_turn compatibility path; facts still require player confirm.",
    ),
    _cli_v1_subcommand_entry(
        "player confirm",
        category="player_workflow",
        taxonomy_category="player-safe",
        profile="player_turn_commit",
        write_mode="validated_commit",
        write_authority="commit only the matching pending player action through SaveManager.player_confirm",
        intended_caller="local player host",
        default_exposed=True,
        normal_play=True,
        description="Confirm and save the pending player action.",
        forbidden_bypasses=PLAYER_SAFE_BYPASSES,
        authority_gate="Requires matching pending action session_id and active save.",
    ),
    _cli_v1_subcommand_entry(
        "player new",
        category="player_registry",
        taxonomy_category="player-safe",
        profile="player_controlled_create",
        write_mode="controlled_create",
        write_authority="create and activate a new save package without gameplay fact commit",
        intended_caller="local player host",
        default_exposed=True,
        normal_play=True,
        description="Create and activate a new save.",
        forbidden_bypasses=PLAYER_SAFE_BYPASSES,
    ),
    _cli_v1_subcommand_entry(
        "player switch",
        category="player_registry",
        taxonomy_category="player-safe",
        profile="player_controlled_selection",
        write_mode="controlled_selection",
        write_authority="switch active save registry selection only",
        intended_caller="local player host",
        default_exposed=True,
        normal_play=True,
        description="Switch active save.",
        forbidden_bypasses=PLAYER_SAFE_BYPASSES,
    ),
    _cli_v1_subcommand_entry(
        "player duplicate",
        category="player_registry",
        taxonomy_category="player-safe",
        profile="player_controlled_create",
        write_mode="controlled_create",
        write_authority="duplicate save package and update active selection without gameplay fact commit",
        intended_caller="local player host",
        default_exposed=True,
        normal_play=True,
        description="Duplicate an existing save and activate the copy.",
        forbidden_bypasses=PLAYER_SAFE_BYPASSES,
    ),
    _cli_v1_subcommand_entry(
        "platform message",
        category="platform_sidecar",
        taxonomy_category="platform sidecar",
        profile="platform_message_forwarder",
        write_mode="advisory_forward",
        write_authority="forward platform message to prewarm service only",
        intended_caller="local platform adapter host",
        description="Handle one platform message event for prewarm.",
        forbidden_bypasses=PLATFORM_SIDECAR_BYPASSES,
        authority_gate="Platform message identity normalization before prewarm forwarding.",
    ),
    _cli_v1_subcommand_entry(
        "platform start",
        category="platform_sidecar",
        taxonomy_category="platform sidecar",
        profile="platform_player_entry",
        write_mode="gate_and_forward",
        write_authority="forward start/continue to SaveManager after platform identity handling",
        intended_caller="local platform adapter host",
        description="Start or continue a game from a platform message.",
        forbidden_bypasses=PLATFORM_SIDECAR_BYPASSES,
        authority_gate="Platform binding and SaveManager start_or_continue gate.",
    ),
    _cli_v1_subcommand_entry(
        "platform act",
        category="platform_sidecar",
        taxonomy_category="platform sidecar",
        profile="platform_player_entry",
        write_mode="gate_and_forward",
        write_authority="forward player text to SaveManager.player_turn with passive preflight identity",
        intended_caller="local platform adapter host",
        description="Run player action from a platform message.",
        forbidden_bypasses=PLATFORM_SIDECAR_BYPASSES,
        authority_gate="Session/actor binding, pending conflict, and SaveManager.player_turn gate.",
    ),
    _cli_v1_subcommand_entry(
        "platform confirm",
        category="platform_sidecar",
        taxonomy_category="platform sidecar",
        profile="platform_player_entry",
        write_mode="gate_and_forward",
        write_authority="forward confirmation to SaveManager.player_confirm with platform identity",
        intended_caller="local platform adapter host",
        description="Confirm a pending player action from a platform message.",
        forbidden_bypasses=PLATFORM_SIDECAR_BYPASSES,
        authority_gate="Session/actor binding plus pending action session_id gate.",
    ),
    _cli_v1_subcommand_entry(
        "platform metrics",
        category="platform_sidecar",
        taxonomy_category="platform sidecar",
        profile="platform_operator_read",
        write_mode="read_only",
        write_authority="read platform sidecar canary metrics only",
        intended_caller="local platform adapter host",
        description="Print platform sidecar canary metrics.",
        forbidden_bypasses=PLATFORM_SIDECAR_BYPASSES,
    ),
    _cli_v1_subcommand_entry(
        "platform expire",
        category="platform_sidecar",
        taxonomy_category="platform sidecar",
        profile="platform_operator_maintenance",
        write_mode="binding_maintenance",
        write_authority="expire stale platform session bindings only",
        intended_caller="local platform adapter host",
        description="Expire stale platform game-session bindings.",
        forbidden_bypasses=PLATFORM_SIDECAR_BYPASSES,
        authority_gate="Platform sidecar binding store only; never writes gameplay facts.",
    ),
    _cli_v1_subcommand_entry(
        "platform deactivate",
        category="platform_sidecar",
        taxonomy_category="platform sidecar",
        profile="platform_operator_maintenance",
        write_mode="binding_maintenance",
        write_authority="deactivate one platform session binding only",
        intended_caller="local platform adapter host",
        description="Deactivate one platform game-session binding.",
        forbidden_bypasses=PLATFORM_SIDECAR_BYPASSES,
        authority_gate="Platform/session identity selects only the binding record to deactivate.",
    ),
    _cli_v1_subcommand_entry(
        "eval run",
        category="eval",
        taxonomy_category="maintenance/admin",
        profile="developer_eval",
        write_mode="test_artifacts_only",
        write_authority="run deterministic evals against fixtures or temp campaign copies",
        intended_caller="developer or test maintainer",
        description="Run deterministic intent and MCP transcript evals.",
        forbidden_bypasses=MAINTENANCE_BYPASSES,
        authority_gate="Eval fixtures and temp copies only; no formal current save mutation.",
    ),
)

PACKAGE_SURFACE_INVENTORY = (
    SurfaceEntry(
        name="aigm campaign validate",
        surface="cli_v1",
        category="campaign_package",
        taxonomy_category="maintenance/admin",
        profile="authoring_or_player_read",
        write_mode="read_only",
        write_authority="validate campaign package without mutating it",
        intended_caller="author, player host, or maintainer",
        default_exposed=False,
        normal_play=False,
        description="Validate a V1 campaign package.",
        forbidden_bypasses=MAINTENANCE_BYPASSES,
    ),
    SurfaceEntry(
        name="aigm campaign test",
        surface="cli_v1",
        category="campaign_package",
        taxonomy_category="maintenance/admin",
        profile="authoring_or_maintenance",
        write_mode="temp_save_only",
        write_authority="create temporary save for smoke checks only",
        intended_caller="author or maintainer",
        default_exposed=False,
        normal_play=False,
        description="Initialize a temporary save and run V1 smoke checks.",
        forbidden_bypasses=MAINTENANCE_BYPASSES,
    ),
    SurfaceEntry(
        name="aigm campaign new",
        surface="cli_v1",
        category="campaign_package",
        taxonomy_category="maintenance/admin",
        profile="authoring",
        write_mode="controlled_create",
        write_authority="create campaign author files in requested target directory",
        intended_caller="campaign author",
        default_exposed=False,
        normal_play=False,
        description="Create an author-friendly campaign from a template.",
        forbidden_bypasses=MAINTENANCE_BYPASSES,
    ),
    SurfaceEntry(
        name="aigm campaign doctor",
        surface="cli_v1",
        category="campaign_package",
        taxonomy_category="maintenance/admin",
        profile="authoring_or_maintenance",
        write_mode="read_only",
        write_authority="run campaign diagnostics without mutating package or save state",
        intended_caller="author or maintainer",
        default_exposed=False,
        normal_play=False,
        description="Run author-facing campaign diagnostics.",
        forbidden_bypasses=MAINTENANCE_BYPASSES,
    ),
    SurfaceEntry(
        name="aigm save init",
        surface="cli_v1",
        category="save_package",
        taxonomy_category="maintenance/admin",
        profile="player_or_maintenance_create",
        write_mode="controlled_create",
        write_authority="initialize save package structure from a campaign package",
        intended_caller="local player host or maintainer",
        default_exposed=False,
        normal_play=False,
        description="Initialize a save directory from a campaign package.",
        notes=("Creates save package structure; does not commit player turn facts.",),
        forbidden_bypasses=MAINTENANCE_BYPASSES,
    ),
    SurfaceEntry(
        name="aigm save inspect",
        surface="cli_v1",
        category="save_package",
        taxonomy_category="player-safe",
        profile="player_read",
        write_mode="read_only",
        write_authority="inspect save package without mutating gameplay facts",
        intended_caller="local player host",
        default_exposed=False,
        normal_play=True,
        description="Inspect a save directory.",
        forbidden_bypasses=PLAYER_SAFE_BYPASSES,
    ),
    SurfaceEntry(
        name="aigm save validate",
        surface="cli_v1",
        category="save_package",
        taxonomy_category="player-safe",
        profile="player_read",
        write_mode="read_only",
        write_authority="validate save package without mutating gameplay facts",
        intended_caller="local player host",
        default_exposed=False,
        normal_play=True,
        description="Validate a save directory.",
        forbidden_bypasses=PLAYER_SAFE_BYPASSES,
    ),
    SurfaceEntry(
        name="aigm save export",
        surface="cli_v1",
        category="save_package",
        taxonomy_category="maintenance/admin",
        profile="maintenance_export",
        write_mode="export_only",
        write_authority="export save archive without changing source save facts",
        intended_caller="maintainer",
        default_exposed=False,
        normal_play=False,
        description="Export a campaign save archive.",
        forbidden_bypasses=MAINTENANCE_BYPASSES,
    ),
    SurfaceEntry(
        name="aigm save import",
        surface="cli_v1",
        category="save_package",
        taxonomy_category="maintenance/admin",
        profile="maintenance_import",
        write_mode="controlled_import",
        write_authority="import save archive into explicit target directory after confirmation",
        intended_caller="maintainer",
        default_exposed=False,
        normal_play=False,
        description="Import a save archive into a target directory.",
        forbidden_bypasses=MAINTENANCE_BYPASSES,
        authority_gate="Requires --yes confirmation and target directory boundary checks.",
    ),
    SurfaceEntry(
        name="aigm save patch",
        surface="cli_v1",
        category="save_package",
        taxonomy_category="maintenance/admin",
        profile="maintenance_repair",
        write_mode="maintenance_write",
        write_authority="apply explicit maintenance patch to a save with backup by default",
        intended_caller="maintainer",
        default_exposed=False,
        normal_play=False,
        description="Apply a safe maintenance patch to a save.",
        forbidden_bypasses=MAINTENANCE_BYPASSES,
        authority_gate="Maintenance patch file plus default pre-patch backup; not a player action path.",
    ),
    SurfaceEntry(
        name="aigm package upgrade",
        surface="cli_admin",
        category="campaign_package",
        taxonomy_category="maintenance/admin",
        profile="admin_maintenance",
        write_mode="admin_write",
        write_authority="apply or dry-run package upgrade against a campaign save",
        intended_caller="admin maintainer",
        default_exposed=False,
        normal_play=False,
        description="Apply or dry-run a package upgrade against a campaign save.",
        forbidden_bypasses=MAINTENANCE_BYPASSES,
        authority_gate="Dry-run path is read-only; apply path requires package diff and backup.",
    ),
    SurfaceEntry(
        name="aigm package install",
        surface="cli_admin",
        category="campaign_package",
        taxonomy_category="maintenance/admin",
        profile="admin_maintenance",
        write_mode="admin_write",
        write_authority="install package into a new campaign or adopt an existing package lock",
        intended_caller="admin maintainer",
        default_exposed=False,
        normal_play=False,
        description="Install a package or adopt an existing campaign package lock.",
        forbidden_bypasses=MAINTENANCE_BYPASSES,
        authority_gate="Explicit campaign/package paths; --adopt-existing requires reconcile-clean adoption, --force is explicit.",
    ),
    SurfaceEntry(
        name="aigm package reconcile",
        surface="cli_admin",
        category="campaign_package",
        taxonomy_category="maintenance/admin",
        profile="admin_read",
        write_mode="read_only",
        write_authority="check whether an initialized campaign can safely adopt a package lock",
        intended_caller="admin maintainer",
        default_exposed=False,
        normal_play=False,
        description="Check package adoption safety without mutating campaign or save state.",
        forbidden_bypasses=MAINTENANCE_BYPASSES,
    ),
    SurfaceEntry(
        name="aigm proposal apply",
        surface="cli_admin",
        category="proposal_queue",
        taxonomy_category="maintenance/admin",
        profile="maintenance_content_apply",
        write_mode="maintenance_write",
        write_authority="apply approved content_delta proposal with backup and projection refresh",
        intended_caller="admin maintainer",
        default_exposed=False,
        normal_play=False,
        description="Apply an approved queued content proposal.",
        forbidden_bypasses=MAINTENANCE_BYPASSES,
        authority_gate="Requires approved proposal status, content_delta kind, backup, and proposal apply audit.",
    ),
    SurfaceEntry(
        name="aigm apply-content-delta",
        surface="cli_admin",
        category="content_delta",
        taxonomy_category="maintenance/admin",
        profile="maintenance_content_apply",
        write_mode="maintenance_write",
        write_authority="apply explicit non-turn content maintenance delta with backup/projection evidence",
        intended_caller="admin maintainer",
        default_exposed=False,
        normal_play=False,
        description="Apply a non-turn content maintenance delta.",
        forbidden_bypasses=MAINTENANCE_BYPASSES,
        authority_gate="Optional strict review blocks high-impact content unless reviewed_by metadata is present.",
    ),
    SurfaceEntry(
        name="aigm save-turn",
        surface="cli_admin",
        category="turn_low_level",
        taxonomy_category="maintenance/admin",
        profile="admin_or_legacy_save_turn",
        write_mode="legacy_validated_commit",
        write_authority="commit one legacy structured turn delta after validation, backup, and post-check",
        intended_caller="admin maintainer or legacy migration operator",
        default_exposed=False,
        normal_play=False,
        description="Legacy structured turn save path.",
        forbidden_bypasses=MAINTENANCE_BYPASSES,
        authority_gate="Validation pipeline, state audit, backup, post-check, and projection evidence are required.",
    ),
    SurfaceEntry(
        name="aigm migrate apply",
        surface="cli_admin",
        category="database_migration",
        taxonomy_category="maintenance/admin",
        profile="admin_maintenance",
        write_mode="admin_write",
        write_authority="apply pending schema migrations",
        intended_caller="admin maintainer",
        default_exposed=False,
        normal_play=False,
        description="Apply pending schema migrations.",
        forbidden_bypasses=MAINTENANCE_BYPASSES,
        authority_gate="Admin migration command only; schema migration must not substitute gameplay writes.",
    ),
    SurfaceEntry(
        name="aigm projection repair",
        surface="cli_admin",
        category="projection",
        taxonomy_category="projection/outbox",
        profile="admin_maintenance",
        write_mode="maintenance_write",
        write_authority="retry outbox and rebuild dirty post-commit projections",
        intended_caller="admin maintainer",
        default_exposed=False,
        normal_play=False,
        description="Retry outbox and rebuild dirty projections.",
        forbidden_bypasses=PROJECTION_BYPASSES,
        authority_gate="Projection repair is maintenance-only and never fact authority.",
    ),
    SurfaceEntry(
        name="aigm plugin validate",
        surface="cli_admin",
        category="plugin",
        taxonomy_category="maintenance/admin",
        profile="admin_read",
        write_mode="read_only",
        write_authority="inspect and validate plugin manifests without loading code",
        intended_caller="admin maintainer",
        default_exposed=False,
        normal_play=False,
        description="Inspect and validate plugin manifests without loading code.",
        forbidden_bypasses=MAINTENANCE_BYPASSES,
    ),
)

RUNTIME_API_SURFACE_INVENTORY = (
    SurfaceEntry(
        name="GMRuntime.preflight_intent",
        surface="runtime_api",
        category="intent_preflight",
        taxonomy_category="trusted low-level",
        profile="developer_or_trusted_gm_advisory_cache",
        write_mode="advisory_only",
        write_authority="create advisory preflight cache state only",
        intended_caller="trusted runtime caller",
        default_exposed=False,
        normal_play=False,
        description="Runtime helper for identity-bound advisory intent preflight.",
        forbidden_bypasses=TRUSTED_LOW_LEVEL_BYPASSES,
        authority_gate="TTL, identity, and single-use preflight constraints.",
    ),
    SurfaceEntry(
        name="GMRuntime.start_turn",
        surface="runtime_api",
        category="turn_workflow",
        taxonomy_category="trusted low-level",
        profile="developer_or_trusted_gm_context",
        write_mode="read_only",
        write_authority="build context/turn contract without committing facts",
        intended_caller="trusted runtime caller",
        default_exposed=False,
        normal_play=False,
        description="Build context and classify one player turn.",
        forbidden_bypasses=TRUSTED_LOW_LEVEL_BYPASSES,
    ),
    SurfaceEntry(
        name="GMRuntime.query",
        surface="runtime_api",
        category="turn_workflow",
        taxonomy_category="trusted low-level",
        profile="developer_or_trusted_gm_read",
        write_mode="read_only",
        write_authority="read current state through runtime query helpers",
        intended_caller="trusted runtime caller",
        default_exposed=False,
        normal_play=False,
        description="Run a non-mutating runtime query.",
        forbidden_bypasses=TRUSTED_LOW_LEVEL_BYPASSES,
    ),
    SurfaceEntry(
        name="GMRuntime.preview_from_text",
        surface="runtime_api",
        category="turn_workflow",
        taxonomy_category="trusted low-level",
        profile="developer_or_trusted_gm_preview",
        write_mode="preview_only",
        write_authority="preview natural-language player text without saving facts",
        intended_caller="trusted runtime caller",
        default_exposed=False,
        normal_play=False,
        description="Low-level natural-language preview primitive.",
        forbidden_bypasses=TRUSTED_LOW_LEVEL_BYPASSES,
    ),
    SurfaceEntry(
        name="GMRuntime.preview_action",
        surface="runtime_api",
        category="turn_low_level",
        taxonomy_category="trusted low-level",
        profile="developer_or_trusted_gm_low_level",
        write_mode="preview_only",
        write_authority="preview selected action contract without saving facts",
        intended_caller="trusted runtime caller",
        default_exposed=False,
        normal_play=False,
        description="Preview an already-selected action contract.",
        forbidden_bypasses=TRUSTED_LOW_LEVEL_BYPASSES,
    ),
    SurfaceEntry(
        name="GMRuntime.act",
        surface="runtime_api",
        category="turn_workflow",
        taxonomy_category="trusted low-level",
        profile="developer_or_trusted_gm_preview",
        write_mode="preview_only",
        write_authority="compatibility preview wrapper over preview_from_text",
        intended_caller="trusted runtime caller",
        default_exposed=False,
        normal_play=False,
        description="Compatibility runtime action preview wrapper.",
        forbidden_bypasses=TRUSTED_LOW_LEVEL_BYPASSES,
    ),
    SurfaceEntry(
        name="GMRuntime.validate_delta",
        surface="runtime_api",
        category="turn_low_level",
        taxonomy_category="trusted low-level",
        profile="developer_or_trusted_gm_validation",
        write_mode="validation_only",
        write_authority="validate structured delta without saving it",
        intended_caller="trusted runtime caller",
        default_exposed=False,
        normal_play=False,
        description="Validate one structured turn delta.",
        forbidden_bypasses=TRUSTED_LOW_LEVEL_BYPASSES,
    ),
    SurfaceEntry(
        name="GMRuntime.commit_turn",
        surface="runtime_api",
        category="turn_low_level",
        taxonomy_category="trusted low-level",
        profile="developer_or_trusted_gm_commit",
        write_mode="validated_commit",
        write_authority="commit validated and accepted TurnProposal delta",
        intended_caller="trusted runtime caller",
        default_exposed=False,
        normal_play=False,
        description="Commit one validated turn delta through the runtime.",
        forbidden_bypasses=TRUSTED_LOW_LEVEL_BYPASSES,
        authority_gate="Requires validation and accepted TurnProposal; ordinary player commit enters SaveManager.player_confirm.",
    ),
)

PLATFORM_SURFACE_INVENTORY = (
    SurfaceEntry(
        name="PlatformSidecar.handle_message_event",
        surface="platform",
        category="platform_sidecar",
        taxonomy_category="platform sidecar",
        profile="platform_message_forwarder",
        write_mode="advisory_forward",
        write_authority="forward platform message to prewarm service only",
        intended_caller="platform sidecar process",
        default_exposed=False,
        normal_play=False,
        description="Handle a platform message event for passive prewarm.",
        forbidden_bypasses=PLATFORM_SIDECAR_BYPASSES,
        authority_gate="Platform message identity normalization before prewarm forwarding.",
    ),
    SurfaceEntry(
        name="PlatformSidecar.start_or_continue_from_message",
        surface="platform",
        category="platform_sidecar",
        taxonomy_category="platform sidecar",
        profile="platform_player_entry",
        write_mode="gate_and_forward",
        write_authority="forward start/continue to SaveManager after platform identity handling",
        intended_caller="platform sidecar process",
        default_exposed=False,
        normal_play=False,
        description="Start or continue a game from a platform message.",
        forbidden_bypasses=PLATFORM_SIDECAR_BYPASSES,
        authority_gate="Platform binding and SaveManager start_or_continue gate.",
    ),
    SurfaceEntry(
        name="PlatformSidecar.player_act_from_message",
        surface="platform",
        category="platform_sidecar",
        taxonomy_category="platform sidecar",
        profile="platform_player_entry",
        write_mode="gate_and_forward",
        write_authority="forward player text to SaveManager.player_turn with passive preflight identity",
        intended_caller="platform sidecar process",
        default_exposed=False,
        normal_play=False,
        description="Run player_turn from a platform message.",
        forbidden_bypasses=PLATFORM_SIDECAR_BYPASSES,
        authority_gate="Session/actor binding, pending conflict, and SaveManager.player_turn gate.",
    ),
    SurfaceEntry(
        name="PlatformSidecar.player_confirm_from_message",
        surface="platform",
        category="platform_sidecar",
        taxonomy_category="platform sidecar",
        profile="platform_player_entry",
        write_mode="gate_and_forward",
        write_authority="forward confirmation to SaveManager.player_confirm with platform identity",
        intended_caller="platform sidecar process",
        default_exposed=False,
        normal_play=False,
        description="Confirm a pending action from a platform message.",
        forbidden_bypasses=PLATFORM_SIDECAR_BYPASSES,
        authority_gate="Session/actor binding plus pending action session_id gate.",
    ),
    SurfaceEntry(
        name="PlatformSidecar.metrics_snapshot",
        surface="platform",
        category="platform_sidecar",
        taxonomy_category="platform sidecar",
        profile="platform_operator_read",
        write_mode="read_only",
        write_authority="read platform sidecar canary metrics only",
        intended_caller="platform operator",
        default_exposed=False,
        normal_play=False,
        description="Return platform sidecar metrics.",
        forbidden_bypasses=PLATFORM_SIDECAR_BYPASSES,
    ),
    SurfaceEntry(
        name="PlatformSidecar.expire_stale_bindings",
        surface="platform",
        category="platform_sidecar",
        taxonomy_category="platform sidecar",
        profile="platform_operator_maintenance",
        write_mode="binding_maintenance",
        write_authority="expire stale platform session bindings only",
        intended_caller="platform sidecar process or operator",
        default_exposed=False,
        normal_play=False,
        description="Expire stale platform game-session bindings.",
        forbidden_bypasses=PLATFORM_SIDECAR_BYPASSES,
        authority_gate="Platform sidecar binding store only; never writes gameplay facts.",
    ),
    SurfaceEntry(
        name="PlatformSidecar.deactivate_from_message",
        surface="platform",
        category="platform_sidecar",
        taxonomy_category="platform sidecar",
        profile="platform_operator_maintenance",
        write_mode="binding_maintenance",
        write_authority="deactivate one platform session binding only",
        intended_caller="platform operator",
        default_exposed=False,
        normal_play=False,
        description="Deactivate one platform game-session binding.",
        forbidden_bypasses=PLATFORM_SIDECAR_BYPASSES,
        authority_gate="Platform/session identity selects only the binding record to deactivate.",
    ),
    SurfaceEntry(
        name="PlatformPrewarmService.handle_message",
        surface="platform",
        category="platform_prewarm",
        taxonomy_category="platform prewarm",
        profile="platform_prewarm",
        write_mode="advisory_only",
        write_authority="enqueue or drop advisory prewarm work only",
        intended_caller="platform sidecar process",
        default_exposed=False,
        normal_play=False,
        description="Handle a platform message for passive advisory prewarm.",
        forbidden_bypasses=PLATFORM_PREWARM_BYPASSES,
        authority_gate="Message identity, binding, queue, TTL, and message_only preflight policy.",
    ),
)

PROJECTION_OUTBOX_SURFACE_INVENTORY = (
    SurfaceEntry(
        name="ProjectionService.refresh",
        surface="projection/outbox",
        category="projection_service",
        taxonomy_category="projection/outbox",
        profile="maintenance_projection",
        write_mode="projection_refresh",
        write_authority="refresh post-commit projection and outbox artifacts",
        intended_caller="kernel service or maintainer",
        default_exposed=False,
        normal_play=False,
        description="Refresh projection and outbox state through ProjectionService.",
        forbidden_bypasses=PROJECTION_BYPASSES,
        authority_gate="Post-commit projection refresh only; source facts remain SQLite/commit-service owned.",
    ),
    SurfaceEntry(
        name="refresh_projections",
        surface="projection/outbox",
        category="projection_helper",
        taxonomy_category="projection/outbox",
        profile="maintenance_projection",
        write_mode="projection_refresh",
        write_authority="refresh selected post-commit projections",
        intended_caller="kernel service or maintainer",
        default_exposed=False,
        normal_play=False,
        description="Refresh selected projection artifacts.",
        forbidden_bypasses=PROJECTION_BYPASSES,
        authority_gate="Post-commit projection helper only; does not authorize fact writes.",
    ),
    SurfaceEntry(
        name="process_outbox",
        surface="projection/outbox",
        category="outbox_helper",
        taxonomy_category="projection/outbox",
        profile="maintenance_projection",
        write_mode="outbox_processing",
        write_authority="process pending or failed outbox items after commit",
        intended_caller="kernel service or maintainer",
        default_exposed=False,
        normal_play=False,
        description="Process projection outbox items.",
        forbidden_bypasses=PROJECTION_BYPASSES,
        authority_gate="Processes pending/failed outbox rows after commit; never rolls facts back.",
    ),
    SurfaceEntry(
        name="render_projection_status",
        surface="projection/outbox",
        category="projection_status",
        taxonomy_category="projection/outbox",
        profile="operator_read",
        write_mode="read_only",
        write_authority="read projection/outbox status only",
        intended_caller="operator or maintainer",
        default_exposed=False,
        normal_play=False,
        description="Render projection and outbox status.",
        forbidden_bypasses=PROJECTION_BYPASSES,
    ),
    SurfaceEntry(
        name="aigm projection status",
        surface="projection/outbox_cli",
        category="projection",
        taxonomy_category="projection/outbox",
        profile="operator_read",
        write_mode="read_only",
        write_authority="read projection/outbox status only",
        intended_caller="operator or maintainer",
        default_exposed=False,
        normal_play=False,
        description="Show projection and outbox status.",
        forbidden_bypasses=PROJECTION_BYPASSES,
    ),
)


def mcp_default_tool_names() -> tuple[str, ...]:
    return tuple(entry.name for entry in MCP_SURFACE_INVENTORY if entry.default_exposed)


def all_surface_entries() -> tuple[SurfaceEntry, ...]:
    return (
        MCP_SURFACE_INVENTORY
        + AI_PROMPT_SURFACE_INVENTORY
        + CLI_V1_COMMAND_SURFACE_INVENTORY
        + CLI_V1_SUBCOMMAND_SURFACE_INVENTORY
        + PACKAGE_SURFACE_INVENTORY
        + RUNTIME_API_SURFACE_INVENTORY
        + PLATFORM_SURFACE_INVENTORY
        + PROJECTION_OUTBOX_SURFACE_INVENTORY
    )


def entries_by_surface(surface: str) -> tuple[SurfaceEntry, ...]:
    return tuple(entry for entry in all_surface_entries() if entry.surface == surface)


def default_mcp_violations(tool_names: tuple[str, ...] | None = None) -> tuple[str, ...]:
    names = tool_names or mcp_default_tool_names()
    violations: list[str] = []
    for name in names:
        lower = name.lower()
        if any(token in lower for token in FORBIDDEN_DEFAULT_MCP_TOKENS):
            violations.append(name)
    return tuple(violations)


def validate_surface_inventory(entries: tuple[SurfaceEntry, ...] | None = None) -> tuple[str, ...]:
    inventory = all_surface_entries() if entries is None else entries
    errors: list[str] = []
    seen: set[tuple[str, str]] = set()
    seen_public_cli_names: set[str] = set()
    for entry in inventory:
        key = (entry.surface, entry.name)
        label = f"{entry.surface}:{entry.name}"
        if key in seen:
            errors.append(f"{label}: duplicate surface entry")
        seen.add(key)
        if entry.name.startswith("aigm "):
            if entry.name in seen_public_cli_names:
                errors.append(f"{label}: duplicate public CLI surface entry")
            seen_public_cli_names.add(entry.name)
        if not entry.taxonomy_category:
            errors.append(f"{label}: missing taxonomy_category")
        elif entry.taxonomy_category not in CANONICAL_TAXONOMY_CATEGORIES:
            errors.append(f"{label}: invalid taxonomy_category {entry.taxonomy_category!r}")
        if not entry.write_authority.strip():
            errors.append(f"{label}: missing write_authority")
        if not entry.intended_caller.strip():
            errors.append(f"{label}: missing intended_caller")
        if isinstance(entry.forbidden_bypasses, str) or not entry.forbidden_bypasses or any(
            not isinstance(item, str) or not item.strip() or item.strip().lower() == "none"
            for item in entry.forbidden_bypasses
        ):
            errors.append(f"{label}: missing forbidden_bypasses")
        if _requires_authority_gate(entry) and not entry.authority_gate.strip():
            errors.append(f"{label}: missing authority_gate")
        if entry.surface == "mcp" and entry.default_exposed and entry.taxonomy_category != "player-safe":
            errors.append(f"{label}: default-exposed MCP entry must be player-safe")
        if entry.taxonomy_category == "player-safe" and _exposes_low_level_authority(entry):
            errors.append(f"{label}: player-safe entry exposes low-level authority")
    return tuple(errors)


def _requires_authority_gate(entry: SurfaceEntry) -> bool:
    mode = entry.write_mode.lower()
    return any(token in mode for token in AUTHORITY_GATE_REQUIRED_WRITE_MODE_TOKENS)


def _exposes_low_level_authority(entry: SurfaceEntry) -> bool:
    low_level_terms = (
        "developer",
        "trusted_gm",
        "maintenance",
        "admin",
        "admin_write",
        "maintenance_write",
        "turn_low_level",
        "low-level",
        "direct low-level",
        "commit_turn",
        "gmruntime.commit_turn",
        "turnproposal",
        "raw delta",
        "validate_delta",
    )
    haystack = " ".join(
        [
            entry.name,
            entry.category,
            entry.profile,
            entry.write_mode,
            entry.write_authority,
            entry.authority_gate,
            " ".join(entry.notes),
        ]
    ).lower()
    if any(term in haystack for term in low_level_terms):
        return True
    if "commit" in entry.write_mode.lower():
        player_confirm_path = "savemanager.player_confirm" in haystack or "pending player action" in haystack
        return not player_confirm_path
    return False


def render_surface_inventory_markdown() -> str:
    lines = [
        "# Phase 0 Surface Inventory",
        "",
        "This inventory is generated from `rpg_engine.surface_inventory`.",
        "",
        "## Default MCP Tools",
        "",
        "| Tool | Category | Taxonomy | Profile | Write mode | Write authority | Normal play | Forbidden bypasses |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for entry in MCP_SURFACE_INVENTORY:
        lines.append(
            f"| `{entry.name}` | {entry.category} | {entry.taxonomy_category} | {entry.profile} | "
            f"{entry.write_mode} | {entry.write_authority} | {entry.normal_play} | "
            f"{', '.join(entry.forbidden_bypasses)} |"
        )
    sections = (
        ("AI Prompt Surfaces", AI_PROMPT_SURFACE_INVENTORY, "File"),
        ("CLI V1 Command Groups", CLI_V1_COMMAND_SURFACE_INVENTORY, "Entry"),
        ("CLI V1 Subcommands", CLI_V1_SUBCOMMAND_SURFACE_INVENTORY, "Entry"),
        ("Package and Maintenance Surfaces", PACKAGE_SURFACE_INVENTORY, "Entry"),
        ("Runtime API Surfaces", RUNTIME_API_SURFACE_INVENTORY, "Entry"),
        ("Platform Surfaces", PLATFORM_SURFACE_INVENTORY, "Entry"),
        ("Projection and Outbox Surfaces", PROJECTION_OUTBOX_SURFACE_INVENTORY, "Entry"),
    )
    for title, entries, first_column in sections:
        lines.extend(
            [
                "",
                f"## {title}",
                "",
                f"| {first_column} | Surface | Category | Taxonomy | Profile | Write mode | Write authority | Gate | Forbidden bypasses |",
                "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
            ]
        )
        for entry in entries:
            lines.append(
                f"| `{entry.name}` | {entry.surface} | {entry.category} | {entry.taxonomy_category} | "
                f"{entry.profile} | {entry.write_mode} | {entry.write_authority} | "
                f"{entry.authority_gate or '-'} | {', '.join(entry.forbidden_bypasses)} |"
            )
    return "\n".join(lines) + "\n"
