#!/usr/bin/env bash
set -euo pipefail

ENV_FILE="${AIGM_PLATFORM_PREWARM_ENV_FILE:-$HOME/.hermes/.aigm-platform-prewarm.env}"

mkdir -p "$(dirname "$ENV_FILE")"

if [[ -z "${DEEPSEEK_API_KEY:-}" ]]; then
  printf "Paste DEEPSEEK_API_KEY: " >&2
  stty -echo
  read -r DEEPSEEK_API_KEY
  stty echo
  printf "\n" >&2
fi

if [[ -z "$DEEPSEEK_API_KEY" ]]; then
  echo "DEEPSEEK_API_KEY is empty; aborting." >&2
  exit 1
fi

umask 077
cat > "$ENV_FILE" <<EOF
# rpg-engine platform prewarm / internal AI
# Generated by scripts/setup_platform_prewarm_env.sh
export DEEPSEEK_API_KEY='$DEEPSEEK_API_KEY'
export AIGM_PLATFORM_PREWARM=1
export AIGM_PLATFORM_PREWARM_INTENT_BACKEND=direct
export AIGM_PLATFORM_PREWARM_INTENT_PROVIDER=deepseek
export AIGM_PLATFORM_PREWARM_INTENT_MODEL=deepseek-v4-flash
export AIGM_PLATFORM_PREWARM_INTENT_BASE_URL=https://api.deepseek.com
export AIGM_PLATFORM_PREWARM_INTENT_API_KEY_ENV=DEEPSEEK_API_KEY
export AIGM_PLATFORM_PREWARM_INTENT_TIMEOUT=8
export AIGM_PLATFORM_PREWARM_INTENT_FALLBACK_BACKEND=off
export AIGM_PLATFORM_PREWARM_QUEUE_SIZE=16
export AIGM_PLATFORM_PREWARM_WORKERS=1
export AIGM_PLATFORM_PREWARM_TTL_SECONDS=300
EOF

chmod 600 "$ENV_FILE"

echo "Wrote $ENV_FILE"
echo "Run this before starting the sidecar/Hermes process:"
echo "  source '$ENV_FILE'"
